import numpy as np
from PIL import Image
from pathlib import Path
import pickle, sys
from scipy.ndimage import center_of_mass

DATASET_FILE = Path("dataset/qmnist/MNIST-120k")
OUTPUT_DIR   = Path("templates")
DIGIT_SIZE   = 28 #عکس ها 28در28 است

KERNELS = {
    "sobel_h":    np.array([[-1,-2,-1],[0,0,0],[1,2,1]],       dtype=np.float32),
    "sobel_v":    np.array([[-1,0,1],[-2,0,2],[-1,0,1]],       dtype=np.float32),
    "diag_tl_br": np.array([[2,-1,-1],[-1,2,-1],[-1,-1,2]],    dtype=np.float32),
    "diag_tr_bl": np.array([[-1,-1,2],[-1,2,-1],[2,-1,-1]],    dtype=np.float32),
    "laplacian":  np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],       dtype=np.float32), #گوشه ها و لبه ها
    "gaussian":   np.array([[1,2,1],[2,4,2],[1,2,1]],           dtype=np.float32)/16.0, #بلور کردن
}


def load_dataset():
    if not DATASET_FILE.exists():
        print(f"ERROR: {DATASET_FILE} not found"); sys.exit(1)
    with open(DATASET_FILE, "rb") as f:
        d = pickle.load(f)
    images = d["data"]
    labels = d["labels"].flatten().astype(np.uint8)
    print(f"{len(images)} samples")
    return images, labels


def center_image(img: np.ndarray) -> np.ndarray: #عکس را سنتر می‌کند تا اگر عکس وسط نبود باز هم تشخیص دهد
    if img.max() < 1e-6:
        return img
    cy, cx = center_of_mass(img)
    dy = int(round(DIGIT_SIZE / 2 - cy))
    dx = int(round(DIGIT_SIZE / 2 - cx))
    result = np.zeros_like(img)
    for y in range(DIGIT_SIZE):
        for x in range(DIGIT_SIZE):
            ny, nx = y + dy, x + dx
            if 0 <= ny < DIGIT_SIZE and 0 <= nx < DIGIT_SIZE:
                result[ny, nx] = img[y, x]
    return result


def preprocess(raw: np.ndarray) -> np.ndarray:
    img = raw.astype(np.float32) / 255.0 #نرمال میکند
    img = np.where(img > 40/255.0, img, 0.0)
    img = center_image(img)
    return img


def write_kernel_header(): #نوشتن کرنل ها در هدر تا کد سی هم از آن استفاده کند
    n = len(KERNELS)
    lines = [
        "/* Auto-generated by mnist_prepare.py -- do not edit */",
        "#pragma once",
        f"#define NUM_KERNELS {n}",
        "#define KERNEL_SIZE 3",
        "",
    ]
    for i, (name, k) in enumerate(KERNELS.items()):
        vals = ", ".join(f"{v:.6f}f" for v in k.flatten())
        lines += [f"/* {i}: {name} */",
                  f"static const float KERNEL_{i}[9] = {{ {vals} }};", ""]
    lines += ["static const float* ALL_KERNELS[NUM_KERNELS] = {"]
    for i in range(n):
        lines.append(f"    KERNEL_{i},")
    lines += ["};", "", "static const char* KERNEL_NAMES[NUM_KERNELS] = {"]
    for name in KERNELS:
        lines.append(f'    "{name}",')
    lines.append("};")
    p = OUTPUT_DIR / "kernels.h"
    p.write_text("\n".join(lines))


def extract_templates(num_per_digit=20): #خروجی گرفتن عکس‌ها از دیتاست باینری
    images, labels = load_dataset()
    OUTPUT_DIR.mkdir(exist_ok=True)
    write_kernel_header()

    total = 0
    for digit in range(10):
        d_dir = OUTPUT_DIR / f"digit_{digit}"
        d_dir.mkdir(exist_ok=True)
        indices = np.where(labels == digit)[0][:num_per_digit]
        for i, idx in enumerate(indices):
            img = preprocess(images[idx])
            arr = (img * 255).clip(0, 255).astype(np.uint8)
            Image.fromarray(arr, mode="L").save(d_dir / f"template_{i}.png")
            total += 1
        print(f"  Digit {digit}: {len(indices)} templates")

    print("=" * 55)
    print(f"Total: {total} templates in {OUTPUT_DIR}/")
    print("=" * 55)
    return total


def create_test_image(num_digits=5, output="test_qmnist.jpg"): #تولید عکس تست
    images, labels = load_dataset()
    canvas = np.full((DIGIT_SIZE, num_digits * DIGIT_SIZE), 255, dtype=np.uint8)
    rng = np.random.default_rng()
    chosen = []
    for i in range(num_digits):
        idx = int(rng.integers(len(images)))
        canvas[:, i*DIGIT_SIZE:(i+1)*DIGIT_SIZE] = 255 - images[idx]
        chosen.append(int(labels[idx]))
        print(f"  Position {i} -> digit {labels[idx]}")
    Image.fromarray(canvas, mode="L").save(output)
    print(f"  Expected sequence: {''.join(map(str,chosen))}")
    print(f"  Saved -> {output}")


def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 20
    if extract_templates(n) > 0:
        create_test_image(5, "test_qmnist.jpg")

if __name__ == "__main__":
    main()