/* Auto-generated by mnist_prepare.py -- do not edit */
#pragma once
#define NUM_KERNELS 6
#define KERNEL_SIZE 3

/* 0: sobel_h */
static const float KERNEL_0[9] = { -1.000000f, -2.000000f, -1.000000f, 0.000000f, 0.000000f, 0.000000f, 1.000000f, 2.000000f, 1.000000f };

/* 1: sobel_v */
static const float KERNEL_1[9] = { -1.000000f, 0.000000f, 1.000000f, -2.000000f, 0.000000f, 2.000000f, -1.000000f, 0.000000f, 1.000000f };

/* 2: diag_tl_br */
static const float KERNEL_2[9] = { 2.000000f, -1.000000f, -1.000000f, -1.000000f, 2.000000f, -1.000000f, -1.000000f, -1.000000f, 2.000000f };

/* 3: diag_tr_bl */
static const float KERNEL_3[9] = { -1.000000f, -1.000000f, 2.000000f, -1.000000f, 2.000000f, -1.000000f, 2.000000f, -1.000000f, -1.000000f };

/* 4: laplacian */
static const float KERNEL_4[9] = { 0.000000f, -1.000000f, 0.000000f, -1.000000f, 4.000000f, -1.000000f, 0.000000f, -1.000000f, 0.000000f };

/* 5: gaussian */
static const float KERNEL_5[9] = { 0.062500f, 0.125000f, 0.062500f, 0.125000f, 0.250000f, 0.125000f, 0.062500f, 0.125000f, 0.062500f };

static const float* ALL_KERNELS[NUM_KERNELS] = {
    KERNEL_0,
    KERNEL_1,
    KERNEL_2,
    KERNEL_3,
    KERNEL_4,
    KERNEL_5,
};

static const char* KERNEL_NAMES[NUM_KERNELS] = {
    "sobel_h",
    "sobel_v",
    "diag_tl_br",
    "diag_tr_bl",
    "laplacian",
    "gaussian",
};